### ISSUE TITLE
TypeError: Cannot set property 'numerator' of undefined

### ISSUE THREAD

**Issue by ratacat** [Uniswap/uniswap-v2-sdk#48]
When trying to instantiate a TokenAmount object from the SDK. I keep getting this error. I'm tried every iteration BigInts, Strings, ethers.utils.parseEther...I can figure it out. It's a 'this' that appears to be undefined. 

`Exception has occurred: TypeError: Cannot set property 'numerator' of undefined
  at Fraction (/Users/jared/Dev/frontman/node_modules/@uniswap/sdk/dist/sdk.cjs.development.js:454:20)
    at CurrencyAmount (/Users/jared/Dev/frontman/node_modules/@uniswap/sdk/dist/sdk.cjs.development.js:575:23)
    at TokenAmount (/Users/jared/Dev/frontman/node_modules/@uniswap/sdk/dist/sdk.cjs.development.js:654:29)
    at betterSlippage (/Users/jared/Dev/frontman/lib/betterSlippage.js:19:14)
    at FullTransactionsSubscription.transactionCatcher (/Users/jared/Dev/frontman/index.js:116:20)
    at FullTransactionsSubscription.emit (/Users/jared/Dev/frontman/node_modules/eventemitter3/index.js:181:35)
    at AlchemyWebSocketProvider.<anonymous> (/Users/jared/Dev/frontman/node_modules/@alch/alchemy-web3/node_modules/web3-core-subscriptions/dist/web3-core-subscriptions.cjs.js:70:18)
    at AlchemyWebSocketProvider.emit (/Users/jared/Dev/frontman/node_modules/eventemitter3/index.js:181:35)
    at AlchemyWebSocketProvider.emitGenericEvent (/Users/jared/Dev/frontman/node_modules/@alch/alchemy-web3/dist/cjs/web3-adapter/webSocketProvider.js:436:14)
    at SturdyWebSocket.AlchemyWebSocketProvider._this.handleMessage (/Users/jared/Dev/frontman/node_modules/@alch/alchemy-web3/dist/cjs/web3-adapter/webSocketProvider.js:207:27)
    at SturdyWebSocket.callListener (/Users/jared/Dev/frontman/node_modules/sturdy-websocket/dist/index.js:338:22)
    at /Users/jared/Dev/frontman/node_modules/sturdy-websocket/dist/index.js:332:61
    at Array.forEach (<anonymous>)
    at SturdyWebSocket.dispatchEventOfType (/Users/jared/Dev/frontman/node_modules/sturdy-websocket/dist/index.js:332:18)
    at SturdyWebSocket.handleMessage (/Users/jared/Dev/frontman/node_modules/sturdy-websocket/dist/index.js:197:14)
    at W3CWebSocket.ws.onmessage (/Users/jared/Dev/frontman/node_modules/sturdy-websocket/dist/index.js:150:56)
    at W3CWebSocket._dispatchEvent [as dispatchEvent] (/Users/jared/Dev/frontman/node_modules/yaeti/lib/EventTarget.js:107:17)
    at W3CWebSocket.onMessage (/Users/jared/Dev/frontman/node_modules/websocket/lib/W3CWebSocket.js:234:14)
    at WebSocketConnection.<anonymous> (/Users/jared/Dev/frontman/node_modules/websocket/lib/W3CWebSocket.js:205:19)
    at WebSocketConnection.emit (events.js:198:13)
    at WebSocketConnection.processFrame (/Users/jared/Dev/frontman/node_modules/websocket/lib/WebSocketConnection.js:554:26)
    at /Users/jared/Dev/frontman/node_modules/websocket/lib/WebSocketConnection.js:323:40`

**Comment by moodysalem** [comment]
Need more info or repro test case, it seems like some kind of `.bind` scoping issue from the stack trace
